# file: C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\coverage\pytracer.py
# hypothesis_version: 6.138.15

[' / ', ' {}', ' | ', '---\nX', '.{:x}.{:x}', '/', '/tmp/debug_trace.txt', '>', '???', 'Empty stack!', 'RESUME', 'RETURN_VALUE', 'YIELD_FROM', 'YIELD_VALUE', 'a', 'call', 'co', 'f_lasti', 'in_atexit', 'line', 'return', 'trace-changed', 'utf-8']